// Provider Presets — pre-configured templates for popular LLM providers
// User just picks a preset + enters API key → connection auto-created

export const PROVIDER_PRESETS = [
  // === Tier 1: Major Providers ===
  {
    id: "openai",
    name: "OpenAI",
    category: "major",
    baseUrl: "https://api.openai.com/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "GPT-4o, GPT-4.1, o3-mini, o4-mini",
    website: "https://openai.com",
    icon: "openai",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    category: "major",
    baseUrl: "https://api.anthropic.com/v1",
    format: "anthropic",
    chatPath: "/messages",
    modelsPath: null,
    authHeader: "x-api-key",
    authPrefix: "",
    extraHeaders: JSON.stringify({ "anthropic-version": "2023-06-01" }),
    description: "Claude Sonnet 4, Claude Opus 4, Claude Haiku",
    website: "https://anthropic.com",
    icon: "anthropic",
    knownModels: [
      { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4", owned_by: "anthropic" },
      { id: "claude-opus-4-20250514", name: "Claude Opus 4", owned_by: "anthropic" },
      { id: "claude-haiku-35-20241022", name: "Claude Haiku 3.5", owned_by: "anthropic" },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "major",
    baseUrl: "https://api.deepseek.com",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "DeepSeek V4, DeepSeek R1, DeepSeek Chat",
    website: "https://deepseek.com",
    icon: "deepseek",
  },
  {
    id: "google-gemini",
    name: "Google Gemini",
    category: "major",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    format: "openai",
    chatPath: "/openai/chat/completions",
    modelsPath: "/openai/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Gemini 2.5 Pro, Gemini 2.0 Flash",
    website: "https://ai.google.dev",
    icon: "google",
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    category: "major",
    baseUrl: "https://api.x.ai/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Grok 3, Grok 3 Mini",
    website: "https://x.ai",
    icon: "xai",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    category: "major",
    baseUrl: "https://api.mistral.ai/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Mistral Large, Codestral, Mistral Medium",
    website: "https://mistral.ai",
    icon: "mistral",
  },

  // === Tier 2: Aggregators & Inference ===
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "aggregator",
    baseUrl: "https://openrouter.ai/api/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    extraHeaders: JSON.stringify({ "HTTP-Referer": "https://lintasan.dev", "X-Title": "Lintasan" }),
    description: "200+ models, pay-per-token aggregator",
    website: "https://openrouter.ai",
    icon: "openrouter",
  },
  {
    id: "groq",
    name: "Groq",
    category: "inference",
    baseUrl: "https://api.groq.com/openai/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Ultra-fast inference: Llama, Mixtral, Gemma",
    website: "https://groq.com",
    icon: "groq",
  },
  {
    id: "together",
    name: "Together AI",
    category: "inference",
    baseUrl: "https://api.together.xyz/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Open-source models: Llama, Qwen, DeepSeek",
    website: "https://together.ai",
    icon: "together",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    category: "inference",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Fast inference: Llama, Mixtral, custom models",
    website: "https://fireworks.ai",
    icon: "fireworks",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    category: "inference",
    baseUrl: "https://api.cerebras.ai/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Fastest inference: Llama 3.3 70B in seconds",
    website: "https://cerebras.ai",
    icon: "cerebras",
  },
  {
    id: "nvidia-nim",
    name: "NVIDIA NIM",
    category: "inference",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "NVIDIA-optimized: Llama, Nemotron, Mixtral",
    website: "https://build.nvidia.com",
    icon: "nvidia",
  },

  // === Tier 3: Chinese Providers ===
  {
    id: "commandcode",
    name: "CommandCode (API Key)",
    category: "chinese",
    baseUrl: "https://api.commandcode.ai",
    format: "commandcode",
    chatPath: "/v1/chat/completions",
    modelsPath: null,
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "CommandCode paid API key",
    website: "https://commandcode.ai",
    icon: "commandcode",
    knownModels: [
      { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro", owned_by: "deepseek" },
      { id: "kimi/kimi-k2.6", name: "Kimi K2.6", owned_by: "moonshot" },
      { id: "glm/glm-4.7", name: "GLM 4.7", owned_by: "zhipu" },
      { id: "minimax/minimax-m2.7", name: "MiniMax M2.7", owned_by: "minimax" },
      { id: "qwen/qwen3-coder", name: "Qwen3 Coder", owned_by: "alibaba" },
      { id: "deepseek/deepseek-r1", name: "DeepSeek R1", owned_by: "deepseek" },
      { id: "deepseek/deepseek-v3", name: "DeepSeek V3", owned_by: "deepseek" },
    ],
  },
  {
    id: "commandcode-alpha",
    name: "CommandCode (Alpha)",
    category: "chinese",
    baseUrl: "https://api.commandcode.ai",
    format: "commandcode",
    chatPath: "/alpha/generate",
    modelsPath: null,
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    extraHeaders: JSON.stringify({ "x-cli-environment": "cli", "x-cli-version": "0.26.25" }),
    description: "Free alpha — token from `cmd auth token`",
    website: "https://commandcode.ai",
    icon: "commandcode",
    knownModels: [
      { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro", owned_by: "deepseek" },
      { id: "kimi/kimi-k2.6", name: "Kimi K2.6", owned_by: "moonshot" },
      { id: "glm/glm-4.7", name: "GLM 4.7", owned_by: "zhipu" },
      { id: "minimax/minimax-m2.7", name: "MiniMax M2.7", owned_by: "minimax" },
      { id: "qwen/qwen3-coder", name: "Qwen3 Coder", owned_by: "alibaba" },
      { id: "deepseek/deepseek-r1", name: "DeepSeek R1", owned_by: "deepseek" },
      { id: "deepseek/deepseek-v3", name: "DeepSeek V3", owned_by: "deepseek" },
    ],
  },
  {
    id: "glm-cn",
    name: "GLM / Zhipu AI",
    category: "chinese",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "GLM-4, CogView, CodeGeeX",
    website: "https://bigmodel.cn",
    icon: "zhipu",
  },
  {
    id: "kimi",
    name: "Kimi / Moonshot",
    category: "chinese",
    baseUrl: "https://api.moonshot.cn/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Kimi K2, Moonshot-v1 (128K context)",
    website: "https://kimi.moonshot.cn",
    icon: "moonshot",
  },
  {
    id: "minimax",
    name: "MiniMax",
    category: "chinese",
    baseUrl: "https://api.minimaxi.com/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "MiniMax M2.7, abab6.5",
    website: "https://minimaxi.com",
    icon: "minimax",
  },
  {
    id: "qwen",
    name: "Qwen / Alibaba",
    category: "chinese",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Qwen3, Qwen-Max, Qwen-Coder",
    website: "https://tongyi.aliyun.com",
    icon: "qwen",
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    category: "chinese",
    baseUrl: "https://api.siliconflow.cn/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Cheap Chinese inference: DeepSeek, Qwen, GLM",
    website: "https://siliconflow.cn",
    icon: "siliconflow",
  },

  // === Tier 4: Other Providers ===
  {
    id: "perplexity",
    name: "Perplexity",
    category: "other",
    baseUrl: "https://api.perplexity.ai",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Sonar: search-augmented LLM responses",
    website: "https://perplexity.ai",
    icon: "perplexity",
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "other",
    baseUrl: "https://api.cohere.ai/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Command R+, Embed, Rerank",
    website: "https://cohere.com",
    icon: "cohere",
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    category: "other",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Serverless inference: Llama, Mistral, Qwen",
    website: "https://deepinfra.com",
    icon: "deepinfra",
  },
  {
    id: "sambanova",
    name: "SambaNova",
    category: "other",
    baseUrl: "https://api.sambanova.ai/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Fast inference on custom hardware",
    website: "https://sambanova.ai",
    icon: "sambanova",
  },
  {
    id: "nebius",
    name: "Nebius AI",
    category: "other",
    baseUrl: "https://api.studio.nebius.ai/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "EU-hosted inference: Llama, Qwen, DeepSeek",
    website: "https://nebius.ai",
    icon: "nebius",
  },
  {
    id: "ollama-local",
    name: "Ollama (Local)",
    category: "self-hosted",
    baseUrl: "http://localhost:11434/v1",
    format: "openai",
    chatPath: "/chat/completions",
    modelsPath: "/models",
    authHeader: "",
    authPrefix: "",
    description: "Local models via Ollama",
    website: "https://ollama.com",
    icon: "ollama",
    noAuth: true,
  },
  {
    id: "custom",
    name: "Custom (OpenAI-compatible)",
    category: "self-hosted",
    baseUrl: "",
    format: "openai",
    chatPath: "/v1/chat/completions",
    modelsPath: "/v1/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "Any OpenAI-compatible endpoint",
    website: "",
    icon: "custom",
  },

  // === Indonesia Providers ===
  {
    id: "sumopod",
    name: "Sumopod",
    category: "indonesia",
    baseUrl: "https://ai.sumopod.com",
    format: "openai",
    chatPath: "/v1/chat/completions",
    modelsPath: "/v1/models",
    authHeader: "Authorization",
    authPrefix: "Bearer ",
    description: "53 models: GPT-5, Claude, DeepSeek, Gemini, Qwen, GLM, Kimi, MiniMax",
    website: "https://sumopod.com",
    icon: "sumopod",
  },
];

export const PRESET_CATEGORIES = [
  { id: "major", name: "Major Providers" },
  { id: "aggregator", name: "Aggregators" },
  { id: "inference", name: "Fast Inference" },
  { id: "chinese", name: "Chinese Providers" },
  { id: "indonesia", name: "Indonesia Providers" },
  { id: "other", name: "Other Providers" },
  { id: "self-hosted", name: "Self-Hosted" },
];

export function getPreset(id) {
  return PROVIDER_PRESETS.find(p => p.id === id) || null;
}

export function getPresetsByCategory(category) {
  return PROVIDER_PRESETS.filter(p => p.category === category);
}
